import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import { runGeminiAdapter } from './gemini';
import { runAnthropicAdapter } from './anthropic';

export interface MemorySession {
  sessionId: string;
  createdAt: string;
  updatedAt: string;
  facts: string[]; // High-density list of facts discovered in the session
  variables: Record<string, string>; // Shared variables/config keys discovered
  rawLogs: { agent: string; summary: string }[];
}

export class SwarmMemoryStore {
  private memoryDir: string;

  constructor() {
    this.memoryDir = join(process.cwd(), '.swarm', 'memory');
    this.ensureDirectoryExists();
  }

  private ensureDirectoryExists() {
    if (!existsSync(join(process.cwd(), '.swarm'))) {
      mkdirSync(join(process.cwd(), '.swarm'));
    }
    if (!existsSync(this.memoryDir)) {
      mkdirSync(this.memoryDir);
    }
  }

  /**
   * Load memory session from disk or create a new one.
   */
  public getOrCreateSession(sessionId: string): MemorySession {
    const filePath = join(this.memoryDir, `${sessionId}.json`);
    
    if (existsSync(filePath)) {
      try {
        const raw = readFileSync(filePath, 'utf8');
        return JSON.parse(raw);
      } catch (e) {
        console.warn(`[MemoryStore] Failed to read memory file for ${sessionId}. Resetting.`);
      }
    }

    const newSession: MemorySession = {
      sessionId,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      facts: [],
      variables: {},
      rawLogs: [],
    };
    
    this.saveSession(newSession);
    return newSession;
  }

  /**
   * Save the memory session back to disk.
   */
  public saveSession(session: MemorySession): void {
    this.ensureDirectoryExists();
    const filePath = join(this.memoryDir, `${session.sessionId}.json`);
    try {
      session.updatedAt = new Date().toISOString();
      writeFileSync(filePath, JSON.stringify(session, null, 2), 'utf8');
    } catch (e: any) {
      console.error(`[MemoryStore] Error writing session memory to disk:`, e.message);
    }
  }

  /**
   * Formats the memory store as a system instruction segment to inject into an agent.
   */
  public injectMemoryIntoPrompt(systemPrompt: string, sessionId: string): string {
    const session = this.getOrCreateSession(sessionId);
    
    if (session.facts.length === 0 && Object.keys(session.variables).length === 0 && session.rawLogs.length === 0) {
      return systemPrompt;
    }

    let memoryContext = '\n\n=== 🧠 SHARED SWARM SESSION MEMORY ===\n';
    memoryContext += 'You have access to the following persistent session memory generated by preceding agents:\n';

    if (session.facts.length > 0) {
      memoryContext += '\n💡 Core Facts & Context:\n';
      session.facts.forEach(fact => {
        memoryContext += `- ${fact}\n`;
      });
    }

    if (Object.keys(session.variables).length > 0) {
      memoryContext += '\n🔑 Shared Variables & Configurations:\n';
      for (const [key, value] of Object.entries(session.variables)) {
        memoryContext += `- ${key}: "${value}"\n`;
      }
    }

    if (session.rawLogs.length > 0) {
      memoryContext += '\n🔄 Executed Sub-agent Work Log:\n';
      session.rawLogs.forEach(log => {
        memoryContext += `- Agent [${log.agent}]: ${log.summary}\n`;
      });
    }

    memoryContext += '=======================================\n';

    return systemPrompt + memoryContext;
  }

  /**
   * Updates memory after an agent finishes, extracting facts and summaries.
   */
  public async updateMemory(
    sessionId: string,
    agentSlug: string,
    agentOutput: string,
    options: { apiKeyGemini?: string; apiKeyAnthropic?: string }
  ): Promise<void> {
    const session = this.getOrCreateSession(sessionId);

    // If we have API keys, let's call the LLM to perform high-density memory compression
    if (options.apiKeyGemini || options.apiKeyAnthropic) {
      const systemInstruction = `You are the Swarm Memory Supervisor.
Your job is to read an agent's output and extract key facts, configurations, and a 1-sentence summary to save into persistent session memory.
Return ONLY a valid JSON object matching this schema:
{
  "newFacts": ["fact 1", "fact 2"],
  "newVariables": { "key": "value" },
  "summary": "1-sentence summary"
}`;

      const goal = `Agent [${agentSlug}] finished and produced this output:\n"""\n${agentOutput}\n"""\nExtract memory updates now.`;
      let jsonResponse = '';

      try {
        if (options.apiKeyGemini) {
          await runGeminiAdapter({
            goal,
            agentName: 'memory-supervisor',
            systemPrompt: systemInstruction,
            apiKey: options.apiKeyGemini,
            onToken: (t) => { jsonResponse += t; },
          });
        } else if (options.apiKeyAnthropic) {
          await runAnthropicAdapter({
            goal,
            agentName: 'memory-supervisor',
            systemPrompt: systemInstruction,
            apiKey: options.apiKeyAnthropic,
            onToken: (t) => { jsonResponse += t; },
          });
        }

        const cleaned = jsonResponse.replace(/```json/g, '').replace(/```/g, '').trim();
        const update = JSON.parse(cleaned);

        if (Array.isArray(update.newFacts)) {
          session.facts.push(...update.newFacts);
        }
        if (update.newVariables && typeof update.newVariables === 'object') {
          session.variables = { ...session.variables, ...update.newVariables };
        }
        if (update.summary) {
          session.rawLogs.push({ agent: agentSlug, summary: update.summary });
        }
        
        // Remove duplicates in facts
        session.facts = Array.from(new Set(session.facts));

        this.saveSession(session);
        console.log(`[MemoryStore] Successfully updated memory for session ${sessionId} using AI compression.`);
        return;
      } catch (e) {
        console.warn(`[MemoryStore] AI memory extraction failed, falling back to manual append:`, e);
      }
    }

    // Manual heuristic fallback if no key is present
    const firstLine = agentOutput.split('\n')[0] || '';
    const cleanSummary = firstLine.substring(0, 100) || `${agentSlug} executed task.`;
    
    session.rawLogs.push({
      agent: agentSlug,
      summary: cleanSummary + (agentOutput.length > 100 ? '...' : ''),
    });

    // Add high-level heuristic fact
    session.facts.push(`${agentSlug} finished execution and outputted ${agentOutput.length} characters of text.`);

    this.saveSession(session);
    console.log(`[MemoryStore] Updated memory for session ${sessionId} using heuristic fallback.`);
  }
}

// Export a single default instance
export const swarmMemoryStore = new SwarmMemoryStore();
